import {validateAnswer} from '@/lib/quranexa/validation';import {sourcePreview} from '@/lib/quranexa/source-preview';
import {library} from '@/lib/quranexa/corpus';
import {savedSchema} from '@/lib/quranexa/state-validation';
import {verseSource,hadith,duas,quran} from '@/lib/quranexa/sources';
import {database,identity,sameOrigin,fail} from '@/lib/quranexa/server';

export async function GET(){try{const user=await identity();if(!user)return Response.json({items:[],signedIn:false});const r=await database().prepare('SELECT id,kind,value,updated_at AS updatedAt FROM saved_items WHERE user_id=? ORDER BY updated_at DESC LIMIT 500').bind(user).all();return Response.json({signedIn:true,items:r.results.map((i:any)=>({...i,value:JSON.parse(i.value)}))},{headers:{'Cache-Control':'private, no-store'}});}catch{return fail();}}
export async function POST(req:Request){try{if(!sameOrigin(req))return fail(403);const user=await identity();if(!user)return fail(401);const raw=await req.text();if(raw.length>100000)return fail(413);const parsed=savedSchema.safeParse(JSON.parse(raw));if(!parsed.success)return fail(400);const {id,kind}=parsed.data;let value:any=parsed.data.value;
if(kind==='bookmark'){const source=await library.source(value.id);if(!source||id!=='bookmark:'+source.id)return fail(400);value=source;}
if(kind==='chat'){const referenced=new Set(value.turns.flatMap((t:any)=>[...(t.sources||[]),...(t.answer?.sources||[])].map((s:any)=>s.id)));if(referenced.size>80)return fail(400);const cache=new Map<string,any>();async function resolve(id:string){if(cache.has(id))return cache.get(id);if(cache.size>=80)throw Error();const source=await library.source(id);if(!source)throw Error();const preview=sourcePreview(source);cache.set(id,preview);return preview}value={...value,context:value.context?await resolve(value.context.id):null,turns:await Promise.all(value.turns.map(async(t:any)=>{const result={...t};if(t.answer){const sources=await Promise.all(t.answer.sources.map((s:any)=>resolve(s.id)));if(!validateAnswer({claims:t.answer.claims,suggestions:t.answer.suggestions},sources))throw Error();result.answer={...t.answer,sources}}if(t.sources)result.sources=await Promise.all(t.sources.map((s:any)=>resolve(s.id)));return result}))};}
if(kind==='history'){const v=verseSource(value.surah,value.ayah),s=quran.find(x=>x.id===value.surah);if(!v||!s||id!=='history:'+s.id)return fail(400);value={title:v.title,url:v.url,surah:s.id,ayah:v.ayah,total:s.total_verses};}await database().prepare('INSERT INTO saved_items (user_id,id,kind,value,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(user_id,id) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at,kind=excluded.kind').bind(user,id,kind,JSON.stringify(value),Date.now()).run();return Response.json({ok:true});}catch{return fail();}}
export async function DELETE(req:Request){try{if(!sameOrigin(req))return fail(403);const user=await identity();if(!user)return fail(401);const id=new URL(req.url).searchParams.get('id');if(!id||id.length>150)return fail(400);await database().prepare('DELETE FROM saved_items WHERE user_id=? AND id=?').bind(user,id).run();return Response.json({ok:true});}catch{return fail();}}
