import {sourceLabel} from '@/lib/quranexa/labels';
import {Admin} from '@/components/quranexa/admin';import {adminIdentity} from '@/lib/quranexa/admin';
import {Login,Privacy} from '@/components/quranexa/login';
import {library} from '@/lib/quranexa/corpus';import {catalog} from '@/lib/quranexa/corpus-core';import kalmas from '@/data/kalmas.json';import {Source} from '@/lib/quranexa/types';import {notFound} from 'next/navigation';import type {Metadata} from 'next';import {headers} from 'next/headers';
import {Provider} from '@/components/quranexa/context';import {Shell} from '@/components/quranexa/shell';import {Home} from '@/components/quranexa/home';import {QuranIndex,Reader} from '@/components/quranexa/reader';import {HadithLibrary,DuaLibrary,SearchPage,Kalmas} from '@/components/quranexa/library';import {Chat} from '@/components/quranexa/chat';import {SavedPage,SettingsPage} from '@/components/quranexa/account';import {SourceCard} from '@/components/quranexa/passages';import {PageHead} from '@/components/quranexa/controls';
import {quran,surahIndex,verseSource,getSurah,hadith,collections,duas,duaTopics,searchSources} from '@/lib/quranexa/sources';import {Locale} from '@/lib/quranexa/types';import {dictionary} from '@/lib/quranexa/i18n';import {getChatGPTUser} from '@/app/chatgpt-auth';
export const dynamic='force-dynamic';
type Props={params:Promise<{locale:string;path?:string[]}>;searchParams:Promise<Record<string,string|undefined>>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {locale,path=[]}=await params;const s=path[0]==='quran'&&path[1]?getSurah(path[1]):null;const title=s?`${s.transliteration}${path[2]?' '+s.id+':'+path[2]:''} — Quranexa AI`:path[0]?`${path[0][0].toUpperCase()+path[0].slice(1)} — Quranexa AI`:'Quranexa AI — Ask. Read. Understand.';const canonicalPath=s?['quran',s.slug,...path.slice(2)]:path;const tail=canonicalPath.length?'/'+canonicalPath.join('/'):'';return {title,description:'Read the complete Quran in Arabic, English and Urdu. Explore source-grounded Islamic knowledge with Quranexa AI.',alternates:{canonical:`/${locale}${tail}`,languages:{en:`/en${tail}`,ur:`/ur${tail}`,ar:`/ar${tail}`}},openGraph:{title,description:'Ask. Read. Understand.',type:'website'},robots:['ask','profile','settings','bookmarks','history','admin','login'].includes(path[0])?{index:false,follow:false}:undefined};}
export default async function Page({params,searchParams}:Props){const {locale:raw,path=[]}=await params;if(!['en','ur','ar'].includes(raw))notFound();const locale=raw as Locale,d=dictionary(locale),query=await searchParams,user=await getChatGPTUser(),signedIn=!!(await headers()).get('oai-authenticated-user-id');let content;const route=path[0]||'home';
if(route==='home')content=<Home daily={verseSource(94,5)!} popular={[1,2,18,36,55,67].map(id=>surahIndex.find(x=>x.id===id))}/>;
else if(route==='quran'){if(!path[1])content=<QuranIndex index={surahIndex}/>;else{const s=getSurah(path[1]);if(!s)notFound();const ayah=path[2]?Number(path[2]):undefined;if(path[2]&&(!Number.isInteger(ayah)||ayah!<1||ayah!>s.total_verses))notFound();const {verses,...metadata}=s;content=<Reader key={s.id} surah={metadata} verses={verses.map(v=>verseSource(s.id,v.id)!)} initialAyah={ayah} prev={quran[s.id-2]?.slug} next={quran[s.id]?.slug}/>;}}
else if(route==='hadith'){if(path[1]&&!collections.some(c=>c.id===path[1]))notFound();if(path[2]){const s=await library.source(`hadith:${path[1]}:${path[2]}`);if(!s)notFound();content=<><PageHead title={sourceLabel(s,locale)}/><SourceCard source={s}/></>}else {const page=Math.max(1,Math.min(10000,Number(query.page)||1));const result=path[1]?await library.collectionPage(path[1],query.book,page):null;content=<HadithLibrary collections={collections} records={result?.records||[]} collection={path[1]} books={result?.collection.books||[]} page={page} pages={result?.pages||1} book={query.book}/>;}}
else if(route==='duas'){const individual=path[1]&&path[2]?duas.find(s=>s.url===`/duas/${path[1]}/${path[2]}`):null;if(path[2]&&!individual)notFound();if(individual)content=<><PageHead title={d.duas}/><SourceCard source={individual}/></>;else{if(path[1]&&!duaTopics.some(x=>x.id===path[1]))notFound();content=<DuaLibrary topics={duaTopics} duas={duas} category={path[1]}/>;}}
else if(route==='kalmas'){const records=path[1]?kalmas.filter(s=>s.id===`kalma:${path[1]}`):kalmas;if(!records.length)notFound();content=<Kalmas records={records as Source[]}/>;}
else if(route==='tafsir'){const s=await library.source(`tafsir:${path[1]}:${path[2]}:${path[3]}`);if(!s)notFound();content=<><PageHead title={sourceLabel(s,locale)}/><SourceCard source={s}/></>;}
else if(route==='search'||route==='topics'){const q=route==='topics'?(path[1]||''):(query.q||'').slice(0,200);content=<SearchPage key={q} query={q} results={await library.search(q)}/>;}
else if(route==='ask'){const context=query.context?await library.source(query.context):null;content=<Chat key={query.context||'ask'} initialQuestion={(query.q||'').slice(0,1800)} context={context}/>;}
else if(route==='admin'){if(!await adminIdentity())notFound();content=<Admin/>;}
else if(route==='login')content=<Login/>;
else if(route==='privacy')content=<Privacy/>;
else if(route==='bookmarks')content=<SavedPage kind="bookmark"/>;
else if(route==='history')content=<SavedPage kind="history"/>;
else if(route==='settings'||route==='profile')content=<SettingsPage account={route==='profile'} email={user?.email}/>;
else if(route==='sources')content=<><PageHead title={d.sourcePolicy} description={d.sourceNote}/><div className="prose-panel"><h2>{d.quran}</h2><p>{d.quranSource}</p><p>{(6236).toLocaleString(locale)} {d.ayahs} · {(114).toLocaleString(locale)} {d.surahs}</p><a href="https://github.com/risan/quran-json" target="_blank" rel="noreferrer">{locale==='ur'?'قرآن کا ماخذ · ریسان باگجا پرادانا · انتساب اور یکساں اشتراک کی اجازت':locale==='ar'?'مصدر القرآن · ريسان باغجا برادانا · ترخيص النسب والمشاركة بالمثل':'Quran JSON — Risan Bagja Pradana · CC-BY-SA 4.0'}</a><p>{locale==='en'?'Arabic text and translations are imported unchanged. The three languages were checked for matching verse identifiers and Arabic text. This is structural verification, not independent scholarly review.':locale==='ur'?'عربی متن اور تراجم اصل ماخذ کے مطابق ہیں۔ آیات کے نمبروں اور عربی متن کی مطابقت جانچی گئی ہے۔ یہ فنی تصدیق ہے، آزاد علمی جائزہ نہیں۔':'استُورد النص والترجمات دون تغيير، وفُحص تطابق أرقام الآيات والنص العربي. هذا تحقق بنيوي وليس مراجعة علمية مستقلة.'}</p><h2>{d.hadith}</h2><p>{d.collectionNotice} {d.noGrade}</p><a href="https://github.com/fawazahmed0/hadith-api" target="_blank" rel="noreferrer">{locale==='ur'?'احادیث کا ماخذ · فواز احمد':locale==='ar'?'مصدر الحديث · فواز أحمد':'Hadith API · Fawaz Ahmed'}</a><h2>{d.duas}</h2><p>{d.duaNotice}</p><h2>{d.tafsir}</h2><p>{locale==='ur'?'تفسیر ابن کثیر: اردو اور انگریزی · تفسیر میسر: عربی۔ اصل مآخذ سے شامل کردہ متن، ہر آیت کے ساتھ دستیاب۔':locale==='ar'?'تفسير ابن كثير بالأردية والإنجليزية، والتفسير الميسر بالعربية. نصوص مستوردة من مصادرها لكل آية.':'Ibn Kathir in English and Urdu; Al-Muyassar in Arabic. Imported source text is available for every ayah.'}</p><a href="https://github.com/spa5k/tafsir_api" target="_blank" rel="noreferrer">{d.verifiedSource}</a><p><a href="https://github.com/wafaaelmaandy/Hisn-Muslim-Json" target="_blank" rel="noreferrer">{locale==='en'?'Hisnul Muslim source edition':'حصن المسلم'}</a></p><h2>{d.ask}</h2><p>{locale==='en'?'Explanations use retrieved passages. Citation IDs must match the retrieved records before an answer can be shown. Original scripture is displayed from the source library, separately from AI summaries. Reference validation does not guarantee that every explanation is correct. Please report errors.':locale==='ur'?'وضاحتیں حاصل کردہ حوالوں پر مبنی ہیں۔ حوالوں کی مطابقت جانچنے کے بعد جواب دکھایا جاتا ہے۔ اصل متن اور اے آئی کی وضاحت الگ ہیں۔ حوالوں کی تصدیق ہر وضاحت کی درستگی کی ضمانت نہیں۔ غلطی کی اطلاع دیں۔':'تستند الشروح إلى المقاطع المسترجعة وتُفحص مراجعها قبل العرض. يُعرض النص الأصلي منفصلاً عن شرح الذكاء الاصطناعي. لا يضمن فحص المراجع صحة كل شرح. يرجى الإبلاغ عن الأخطاء.'}</p></div></>;
else notFound();return <Provider locale={locale} user={signedIn}><div dir={locale==='en'?'ltr':'rtl'} lang={locale}><Shell>{content}</Shell></div></Provider>;
}
