import extraDuas from '@/data/duas.json';
import extraDuaTopics from '@/data/dua-categories.json';
import quranData from '@/data/quran.json';
import hadithData from '@/data/hadith.json';
import {Source,Surah} from './types';
export const quran=quranData as Surah[];
export const hadith=(hadithData as Source[]).map(s=>({...s,sourceUrl:s.url,url:'/hadith/'+s.id.split(':').slice(1).join('/')}));
export const surahIndex=quran.map(({verses,...s})=>s);
export const collections=[{id:'bukhari',name:'Sahih al-Bukhari',ar:'صحيح البخاري'},{id:'muslim',name:'Sahih Muslim',ar:'صحيح مسلم'},{id:'abudawud',name:'Sunan Abu Dawood',ar:'سنن أبي داود'},{id:'tirmidhi',name:'Jami’ at-Tirmidhi',ar:'جامع الترمذي'},{id:'nasai',name:'Sunan an-Nasa’i',ar:'سنن النسائي'},{id:'ibnmajah',name:'Sunan Ibn Majah',ar:'سنن ابن ماجه'}];
export function getSurah(key:string){return quran.find(s=>s.slug===key||String(s.id)===key||(key==='al-fatiha'&&s.id===1));}
export function verseSource(s:number,a:number):Source|null{const surah=quran.find(x=>x.id===s),v=surah?.verses.find(x=>x.id===a);if(!surah||!v)return null;return {id:`quran:${s}:${a}`,kind:'quran',title:`${surah.transliteration} ${s}:${a}`,arabic:v.text,en:v.translation,ur:v.urdu,transliteration:v.transliteration,url:`/quran/${surah.slug}/${a}`,surah:s,ayah:a,juz:v.juz,page:v.page,hizb:v.hizb,sajdah:v.sajdah};}
export const duaTopics=[...extraDuaTopics,{id:'guidance',title:['Guidance','ہدایت','الهداية'],refs:[[1,6]]},{id:'parents',title:['For parents','والدین کے لیے','للوالدين'],refs:[[17,24],[14,41]]},{id:'forgiveness',title:['Forgiveness','مغفرت','المغفرة'],refs:[[7,23],[23,118],[66,8]]},{id:'knowledge',title:['Knowledge','علم','العلم'],refs:[[20,114]]},{id:'patience',title:['Patience & difficulties','صبر اور مشکلات','الصبر والشدائد'],refs:[[2,250],[21,87]]},{id:'goodness',title:['Goodness in both worlds','دنیا و آخرت کی بھلائی','خير الدنيا والآخرة'],refs:[[2,201]]},{id:'family',title:['Family','اہل خانہ','الأسرة'],refs:[[25,74],[3,38]]},{id:'faith',title:['Steadfast faith','ایمان پر ثابت قدمی','الثبات على الإيمان'],refs:[[3,8],[3,16]]}];
export const duas:Source[]=[...extraDuas as Source[],...duaTopics.flatMap(t=>('refs' in t?t.refs:[]).map(([s,a])=>({...verseSource(s,a)!,kind:'dua' as const,id:`dua:${s}:${a}`,book:t.id})))];
export function normalize(t:string){return t.replace(/[٠-٩۰-۹]/g,c=>String(c.charCodeAt(0)-(c.charCodeAt(0)>=1776?1776:1632))).toLowerCase().normalize('NFKD').replace(/[\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/[إأآٱ]/g,'ا').replace(/[ىی]/g,'ي').replace(/ک/g,'ك').replace(/[ہھة]/g,'ه').replace(/[ؤئ]/g,'ء');}
const allSources=[...quran.flatMap(s=>s.verses.map(v=>verseSource(s.id,v.id)!)),...hadith,...duas];
const searchable=allSources.map(s=>({s,text:normalize([s.title,s.arabic,s.en,s.ur,s.book].join(' '))}));
export function searchSources(query:string,limit=60){const q=normalize(query.trim());if(!q)return [];const ref=q.match(/^(?:quran\s*)?(\d{1,3}):(\d{1,3})$/);if(ref){const s=verseSource(+ref[1],+ref[2]);return s?[s]:[];}const tokens=q.split(/\s+/).filter(x=>x.length>1);if(!tokens.length)return [];return searchable.map(x=>({...x,score:(x.text.includes(q)?20:0)+tokens.reduce((a,t)=>a+(x.text.includes(t)?1:0),0)})).filter(x=>x.score>=Math.max(1,Math.ceil(tokens.length*.55))).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.s);}
export function retrieve(query:string,context?:string){if(context){const s=allSources.find(x=>x.id===context);if(s)return [s,...searchSources(query,6).filter(x=>x.id!==s.id)].slice(0,8);}const ref=query.match(/(\d{1,3}):(\d{1,3})/);if(ref){const s=verseSource(+ref[1],+ref[2]);return s?[s]:[];}const named=quran.find(s=>normalize(query).includes(normalize(s.transliteration))||normalize(query).includes(normalize(s.name)));if(named)return named.verses.slice(0,12).map(v=>verseSource(named.id,v.id)!);const clean=query.replace(/(?:کے بارے میں|کی وضاحت کریں|تلاش کریں|سوال|ما معنى|اشرح|عن|أعطني)/g,' ').replace(/\b(explain|what|does|mean|meaning|is|the|of|about|give|verses|quranic|islam|say|in|urdu|english|please|find|me)\b/gi,' ').trim();return searchSources(clean,8);}
