'use client';
import {sourceLabel,collectionLabel} from '@/lib/quranexa/labels';
import {useState} from 'react';import Link from 'next/link';import {Bookmark,History,UserRound,Trash2,ArrowUpRight,Settings2,LoaderCircle} from 'lucide-react';import {toast} from 'sonner';
import {Slider} from '@/components/ui/slider';import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {useQ} from './context';import {PageHead,Choice} from './controls';import {SourceCard} from './passages';import {languages,languageOptions} from '@/lib/quranexa/i18n';
export function DeleteButton({id}:{id:string}){const {d,remove}=useQ();return <AlertDialog><AlertDialogTrigger className="icon-button" aria-label={d.delete}><Trash2 size={16}/></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{d.deleteConfirm}</AlertDialogTitle></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{d.cancel}</AlertDialogCancel><AlertDialogAction onClick={()=>remove(id)}>{d.delete}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
export function SavedPage({kind}:{kind:'bookmark'|'history'}){const {locale,d,items,signedIn,ready}=useQ();const rows=items.filter(x=>x.kind===kind);return <><PageHead title={kind==='bookmark'?d.bookmarks:d.history} description={kind==='bookmark'?d.emptyBookmarks:d.emptyHistory}/>{!ready?<div className="empty-state"><LoaderCircle className="spin"/>{d.loading}</div>:!signedIn?<SignIn/>:!rows.length?<div className="empty-state"><BookIcon/><p>{d.emptySub}</p><Link className="button primary" href={`/${locale}/quran`}>{d.read}</Link></div>:<div className="saved-list">{rows.map(r=>kind==='bookmark'?<div key={r.id}><SourceCard source={r.value}/></div>:<div key={r.id} className="history-card"><History size={21}/><Link href={`/${locale}${r.value.url}`}><h3>{r.value.title}</h3><p>{new Date(r.updatedAt).toLocaleDateString(locale)}</p></Link><DeleteButton id={r.id}/></div>)}</div>}</>}
function BookIcon(){return <Bookmark size={32}/>}
export function SignIn(){const {locale,d}=useQ();return <div className="empty-state"><UserRound size={32}/><p>{d.guest}</p><a className="button primary" href={`/${locale}/login`} target="_top">{d.signIn}</a></div>}
export function SettingsPage({account=false,email}:{account?:boolean;email?:string}){const {locale,d,prefs,setPrefs,save,signedIn}=useQ();const [saving,setSaving]=useState(false);const opts=languageOptions(locale);return <><PageHead title={account?d.account:d.settings} description={account?d.accountNote:d.sourcePrivacy}/>{account&&!signedIn?<SignIn/>:<div className="settings-panel">{account&&<div className="profile-info"><span className="profile-avatar"><UserRound size={25}/></span><div><h2>{prefs.name||d.account}</h2><p>{email}</p></div><a className="text-link" href={`/signout-with-chatgpt?return_to=/${locale}`} target="_top">{d.signOut}</a></div>}<div className="setting-row"><label htmlFor="profile-name">{d.name}</label><input id="profile-name" maxLength={80} value={prefs.name} onChange={e=>setPrefs({...prefs,name:e.target.value})}/></div><div className="setting-row"><label>{d.interface}</label><Choice label={d.interface} value={locale} options={opts} onChange={v=>{window.location.href=`/${v}/settings`}}/></div><div className="setting-row"><label>{d.translation}</label><Choice label={d.translation} value={prefs.translation} options={opts.filter(x=>x.value!=='ar')} onChange={v=>setPrefs({...prefs,translation:v as any})}/></div><div className="setting-row"><label>{d.aiLanguage}</label><Choice label={d.aiLanguage} value={prefs.aiLanguage} options={opts} onChange={v=>setPrefs({...prefs,aiLanguage:v as any})}/></div><div className="setting-row"><label>{d.font} <span>{prefs.fontSize.toLocaleString(locale)} {locale==='en'?'px':'نقطہ'}</span></label><Slider value={[prefs.fontSize]} min={24} max={64} step={2} aria-label={d.font} onValueChange={([v])=>setPrefs({...prefs,fontSize:v})}/></div><div className="setting-row"><label>{d.translationFont} <span>{prefs.translationSize.toLocaleString(locale)} {locale==='en'?'px':'نقطہ'}</span></label><Slider value={[prefs.translationSize]} min={16} max={30} onValueChange={([v])=>setPrefs({...prefs,translationSize:v})}/></div><div className="setting-row"><label>{d.appearance}</label><Choice label={d.appearance} value={prefs.theme} options={[{value:'light',label:d.light},{value:'dark',label:d.dark}]} onChange={v=>setPrefs({...prefs,theme:v as any})}/></div><div className="setting-row"><label>{d.readingMode}</label><Choice label={d.readingMode} value={prefs.readingMode} options={[{value:'both',label:d.both},{value:'arabic',label:d.arabic},{value:'translation',label:d.onlyTranslation}]} onChange={v=>setPrefs({...prefs,readingMode:v as any})}/></div><div className="settings-save"><button className="button primary" disabled={saving} onClick={async()=>{setSaving(true);if(await save('preferences','preferences',prefs))toast.success(d.themeSaved);setSaving(false)}}>{saving?<LoaderCircle className="spin" size={17}/>:<Settings2 size={17}/>} {d.save}</button></div></div>}</>}
